ktor:
    development: true
    application:
        modules:
            - cz.regulus.ApplicationKt.module
    deployment:
        watch:
            - classes
            - resources
        port: 8080
