name: Deploy to GCloud on merge
on:
  push:
    branches:
      - none
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i && npm run build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.5
        with:
          credentials_json: ${{ secrets.GCLOUD_JSON }}
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - run: ./gradlew appengineDeploy